// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/ipc/ipc.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IPCMessage is the wire envelope for all inter-process traffic on the UDS
// transport. The transport layer frames and delivers opaque payloads; the
// sender/receiver agree on the payload encoding (RawMessage or CanonicalEvent).
type IPCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "raw" | "canonical" | "control"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // opaque serialized message
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic sequence number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPCMessage) Reset() {
	*x = IPCMessage{}
	mi := &file_pkg_ipc_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPCMessage) ProtoMessage() {}

func (x *IPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPCMessage.ProtoReflect.Descriptor instead.
func (*IPCMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *IPCMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IPCMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IPCMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// RawFrame carries an adapter.RawMessage across the adapter→canonicalizer edge.
// The raw Payload is byte-for-byte identical to wire data (never modified).
type RawFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                               // "BINANCE" | "IB" | ...
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                             // original wire bytes — UNTOUCHED
	ReceivedAt    int64                  `protobuf:"varint,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`    // hardware timestamp (ns since epoch)
	SequenceNum   uint64                 `protobuf:"varint,4,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"` // source sequence number (if available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFrame) Reset() {
	*x = RawFrame{}
	mi := &file_pkg_ipc_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFrame) ProtoMessage() {}

func (x *RawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFrame.ProtoReflect.Descriptor instead.
func (*RawFrame) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *RawFrame) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RawFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RawFrame) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *RawFrame) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

var File_pkg_ipc_ipc_proto protoreflect.FileDescriptor

const file_pkg_ipc_ipc_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/ipc/ipc.proto\x12\x03ipc\"L\n" +
	"\n" +
	"IPCMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x80\x01\n" +
	"\bRawFrame\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\x03R\n" +
	"receivedAt\x12!\n" +
	"\fsequence_num\x18\x04 \x01(\x04R\vsequenceNumB\x1cZ\x1araw-data-layer/pkg/ipc;ipcb\x06proto3"

var (
	file_pkg_ipc_ipc_proto_rawDescOnce sync.Once
	file_pkg_ipc_ipc_proto_rawDescData []byte
)

func file_pkg_ipc_ipc_proto_rawDescGZIP() []byte {
	file_pkg_ipc_ipc_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipc_ipc_proto_rawDesc), len(file_pkg_ipc_ipc_proto_rawDesc)))
	})
	return file_pkg_ipc_ipc_proto_rawDescData
}

var file_pkg_ipc_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ipc_ipc_proto_goTypes = []any{
	(*IPCMessage)(nil), // 0: ipc.IPCMessage
	(*RawFrame)(nil),   // 1: ipc.RawFrame
}
var file_pkg_ipc_ipc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_ipc_ipc_proto_init() }
func file_pkg_ipc_ipc_proto_init() {
	if File_pkg_ipc_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipc_ipc_proto_rawDesc), len(file_pkg_ipc_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ipc_ipc_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_ipc_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_ipc_proto_msgTypes,
	}.Build()
	File_pkg_ipc_ipc_proto = out.File
	file_pkg_ipc_ipc_proto_goTypes = nil
	file_pkg_ipc_ipc_proto_depIdxs = nil
}
